name: lifetime
description: Lifetime flutter project.
homepage: https://github.com/dorofiykolya/flutter-lifetime
version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter: